FROM ruby:2.7.2

RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/' /etc/ssl/openssl.cnf

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

# Utilities
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl git sudo vim telnet iputils-ping ssh openssh-server cron

# executable JS is required
RUN cd ~ \
    && curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh \
    && bash nodesource_setup.sh\
    && apt install nodejs\
    && nodejs -v

# See https://github.com/phusion/passenger-docker/issues/195#issuecomment-321868848
RUN export DEBIAN_FRONTEND=noninteractive; \
    apt-get install -y tzdata

# for postgres
RUN apt-get install -y libpq-dev

# for nokogiri
RUN apt-get install -y libxml2-dev libxslt1-dev

# for imagemagik
RUN apt-get install -y imagemagick

WORKDIR /railsapp

EXPOSE 3000

CMD sleep infinity
