version: 2.1


jobs:
  build:
    working_directory: ~/rails
    docker:
      - image: circleci/ruby:2.6.6-node-browsers-legacy
        environment:
          PGHOST: localhost
          PGUSER: ara
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: ara
          POSTGRES_DB: ara_test
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PASSWORD: ""
    steps:
      - checkout:
          path: ~/rails
      
      - run: cd rails/; ls -la; pwd;
      
      - restore_cache:
          type: cache-restore
          name: Restore bundle cache
          key: clara-bundle2-{{ checksum "rails/Gemfile.lock" }}

      - restore_cache:
          type: cache-restore
          name: Restore yarn cache
          key: clara-yarn2-{{ checksum "rails/yarn.lock" }}

      - run:
          name: Bundle Install
          command: cd rails && bin/bundle install --path /home/circleci/rails/vendor/bundle

      - run:
          name: Yarn Install
          command: cd rails && yarn install

      - save_cache:
          type: cache-save
          name: Store bundle cache
          key: clara-bundle2-{{ checksum "rails/Gemfile.lock" }}
          paths:
            - /home/circleci/rails/vendor/bundle

      - save_cache:
          type: cache-save
          name: Store yarn cache
          key: clara-yarn2-{{ checksum "rails/yarn.lock" }}
          paths:
            - ~/.yarn-cache

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: cd rails && bundle exec rails db:migrate --trace

      - run:
          name: Run Rails tests
          command: cd rails && bundle exec rails test

      - run:
          path: rails
          name: Run JS test
          command: bundle exec teaspoon

      - run:
          name: Run e2e tests
          command: cd rails && bundle exec rails cypress:run COVERAGE_PLEASE=true ARA_URL_GEO_API=/fake_ban_ R7_MODE=true ARA_EMAIL_FROM=no-reply@clara.pole-emploi.fr

      - run:
          name: Merge coverage
          command: cd rails && bundle exec rails ruby_cov:merge

      - store_artifacts:
          path: /home/circleci/rails/rails/coverage
