version: 2.1

jobs:
  build:
    working_directory: ~/rails
    docker:
      - image: circleci/ruby:2.6.0-node-browsers-legacy
        environment:
          PGHOST: localhost
          PGUSER: ara
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: ara
          POSTGRES_DB: ara_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout:
          path: ~/rails

      - restore_cache:
          path: ~/rails
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1

      - run: 
          path: ~/rails
          command: bundle install --path vendor/bundle

      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
            
      - run:
          name: run db migrations
          command: bin/rails db:migrate RAILS_ENV=test

      - run:
          name: run ruby test
          command: bin/rails test

      - run: sudo npm install -g istanbul

      - run:
          name: run JS test
          command: bundle exec teaspoon
