version: 2.1


jobs:
  build:
    working_directory: ~/rails
    docker:
      - image: circleci/ruby:2.6.6-node-browsers-legacy
        environment:
          PGHOST: localhost
          PGUSER: ara
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: ara
          POSTGRES_DB: ara_test
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_PASSWORD: ""
    steps:
      - checkout:
          path: ~/rails

      - run: cd rails/; ls -la; pwd;


      - type: cache-restore
        name: Restore bundle cache
        key: clara-bundle-{{ checksum "rails/Gemfile.lock" }}

      - type: cache-restore
        name: Restore npm cache
        key: clara-npm-{{ checksum "rails/package-lock.json" }}


      - run:
          name: Bundle Install
          command: bin/bundle install --path rails/rails/vendor/bundle

      - run:
          name: Npm Install
          command: npm install rails/rails/node_modules


      - type: cache-save
        name: Store bundle cache
        key: clara-bundle-{{ checksum "rails/Gemfile.lock" }}
        paths:
          - ~/rails/vendor/bundle

      - type: cache-save
        name: Store npm cache
        key: clara-npm-{{ checksum "rails/package-lock.json" }}
        paths:
          - ~/rails/.npm-cache
            
      - run:
          path: rails
          name: run db migrations
          command: bin/rails db:migrate RAILS_ENV=test

      - run:
          path: rails
          name: run ruby test
          command: bin/rails test

      - run:
          path: rails
          command: sudo npm install -g istanbul

      - run:
          path: rails
          name: run JS test
          command: bundle exec teaspoon
