version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.0-node-browsers-legacy
        environment:
          PGHOST: localhost
          PGUSER: ara
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: ara
          POSTGRES_DB: ara_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout # check out the code in the project directory

      - setup_remote_docker: 
         docker_layer_caching: true 

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: clara-42

      # Bundle install dependencies
      - run: gem install bundler -v 1.16.1 && bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: clara-42
        paths:
          - vendor/bundle

      - run: echo "hello world" # run the `echo` command

