version: 2
jobs:
  build:
    working_directory: ~/rails
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: circleci
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: clara_test
    steps:
      - checkout
      
      - run: cd rails/; ls -la; pwd;
      
      - type: cache-restore
        name: Restore bundle cache
        key: clara-bundle-{{ checksum "rails/Gemfile.lock" }}

      - type: cache-restore
        name: Restore npm cache
        key: clara-npm-{{ checksum "rails/package-lock.json" }}

      - run:
          name: Bundle Install
          command: cd rails && bin/bundle install --path vendor/bundle

      - run:
          name: Npm Install
          command: cd rails && npm install

      - type: cache-save
        name: Store bundle cache
        key: clara-bundle-{{ checksum "rails/Gemfile.lock" }}
        paths:
          - rails/vendor/bundle

      - type: cache-save
        name: Store npm cache
        key: clara-npm-{{ checksum "rails/package-lock.json" }}
        paths:
          - rails/rails/node_modules

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: rails/bin/rails db:schema:load --trace

      - run:
          name: Run e2e tests
          command: rails/bin/rails cypress:run

      - run:
          name: Run Rails tests
          command: rails/bin/rails test
