 version: 2
 jobs:
   build:
     working_directory: ~/clara
     docker:
       - image: circleci/ruby:2.6.0-node-browsers
       environment:
         RAILS_ENV: test
     steps:
       - checkout
       - run: echo "A first hello"
       - run: bin/rails test
