version: 2.1


jobs:
  build:
    working_directory: ~/rails
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: circleci
          RAILS_ENV: test
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: ara_test
    steps:
      - checkout
      
      - run: cd rails/; ls -la; pwd;
      
      - type: cache-restore
        name: Restore bundle cache
        key: clara-bundle2-{{ checksum "rails/Gemfile.lock" }}

      - type: cache-restore
        name: Restore yarn cache
        key: clara-yarn2-{{ checksum "rails/yarn.lock" }}

      - run:
          name: Bundle Install
          command: cd rails && bin/bundle install --path /home/circleci/rails/vendor/bundle

      - run:
          name: Yarn Install
          command: cd rails && yarn install

      - type: cache-save
        name: Store bundle cache
        key: clara-bundle2-{{ checksum "rails/Gemfile.lock" }}
        paths:
          - /home/circleci/rails/vendor/bundle

      - type: cache-save
        name: Store yarn cache
        key: clara-yarn2-{{ checksum "rails/yarn.lock" }}
        paths:
          - ~/.yarn-cache

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: cd rails && bundle exec rails db:schema:load --trace

      - run:
          name: Run e2e tests
          command: cd rails && bundle exec rails cypress:run

      - run:
          name: Run Rails tests
          command: cd rails && bundle exec rails test

      - run:
          path: rails
          name: run JS test
          command: bundle exec teaspoon
