require "test_helper"

class FooterTest < ActiveSupport::TestCase
  
  test ".root_condition " do
  end

  def nominal_args
    {:aides=>
  [{"id"=>6,
    "name"=>"Appui à l'embauche",
    "created_at"=>Thu, 31 Aug 2017 12:23:10 UTC +00:00,
    "updated_at"=>Fri, 13 Jul 2018 11:59:37 UTC +00:00,
    "ordre_affichage"=>4,
    "icon"=> "<svg/></svg>",
    "slug"=>"appui-a-l-embauche",
    "category"=>"aide",
    "plural"=>"Appuis à l'embauche"},
   {"id"=>1,
    "name"=>"Aide à la mobilité",
    "created_at"=>Tue, 29 Aug 2017 08:24:42 UTC +00:00,
    "updated_at"=>Fri, 13 Jul 2018 12:00:25 UTC +00:00,
    "ordre_affichage"=>0,
    "icon"=> "<svg/></svg>",
    "slug"=>"aide-a-la-mobilite",
    "category"=>"aide",
    "plural"=>"Aides à la mobilité"},
   {"id"=>3,
    "name"=>"Emploi international",
    "created_at"=>Tue, 29 Aug 2017 08:27:40 UTC +00:00,
    "updated_at"=>Fri, 13 Jul 2018 12:01:49 UTC +00:00,
    "ordre_affichage"=>6,
    "icon"=> "<svg/></svg>",
    "slug"=>"emploi-international",
    "category"=>"aide",
    "plural"=>"Emplois internationaux"},
   {"id"=>2,
    "name"=>"Aide à la création ou reprise d'entreprise",
    "created_at"=>Tue, 29 Aug 2017 08:25:23 UTC +00:00,
    "updated_at"=>Fri, 13 Jul 2018 12:00:57 UTC +00:00,
    "ordre_affichage"=>3,
    "icon"=> "<svg/></svg>",
    "slug"=>"aide-a-la-creation-ou-reprise-d-entreprise",
    "category"=>"aide",
    "plural"=>"Aides à la création ou reprise d'entreprise"},
   {"id"=>10,
    "name"=>"Aide régionale",
    "created_at"=>Mon, 27 Nov 2017 09:54:01 UTC +00:00,
    "updated_at"=>Fri, 13 Jul 2018 12:05:29 UTC +00:00,
    "ordre_affichage"=>100,
    "icon"=> "<svg/></svg>",
    "slug"=>"aide-regionale",
    "category"=>"aide",
    "plural"=>"Aides régionales"}],
 :dispositifs=>
  [{"id"=>4,
    "name"=>
     "Aide à la définition du projet professionnel, à l'orientation, ou à la reconversion",
    "created_at"=>Tue, 29 Aug 2017 08:30:59 UTC +00:00,
    "updated_at"=>Fri, 29 Mar 2019 07:20:36 UTC +00:00,
    "ordre_affichage"=>1,
    "icon"=> "<svg/></svg>",
    "slug"=>"aide-a-la-definition-du-projet-professionnel",
    "category"=>"dispositif",
    "plural"=>
     "Aides à la définition du projet professionnel, à l'orientation, ou à la reconversion"},
   {"id"=>8,
    "name"=>"Dispositif de formation, certification, obtention de diplôme",
    "created_at"=>Fri, 22 Sep 2017 15:13:13 UTC +00:00,
    "updated_at"=>Fri, 29 Mar 2019 06:41:31 UTC +00:00,
    "ordre_affichage"=>7,
    "icon"=> "<svg/></svg>",
    "slug"=>"dispositif-de-conversion-d-experience-en-titre",
    "category"=>"dispositif",
    "plural"=>
     "Dispositifs de  formation, certification, obtention de diplôme"},
   {"id"=>5,
    "name"=>"Contrat spécifique",
    "created_at"=>Tue, 29 Aug 2017 09:21:18 UTC +00:00,
    "updated_at"=>Fri, 13 Jul 2018 12:03:01 UTC +00:00,
    "ordre_affichage"=>5,
    "icon"=> "<svg/></svg>",
    "slug"=>"contrat-specifique",
    "category"=>"dispositif",
    "plural"=>"Contrats spécifiques"},
   {"id"=>9,
    "name"=>"Dispositif Séniors",
    "created_at"=>Thu, 19 Oct 2017 11:46:08 UTC +00:00,
    "updated_at"=>Fri, 13 Jul 2018 12:04:48 UTC +00:00,
    "ordre_affichage"=>8,
    "icon"=> "<svg/></svg>",
    "slug"=>"dispositif-seniors",
    "category"=>"dispositif",
    "plural"=>"Dispositifs Séniors"},
   {"id"=>7,
    "name"=>"Contrat en alternance",
    "created_at"=>Tue, 05 Sep 2017 07:17:45 UTC +00:00,
    "updated_at"=>Fri, 13 Jul 2018 12:03:37 UTC +00:00,
    "ordre_affichage"=>2,
    "icon"=> "<svg/></svg>",
    "slug"=>"contrat-en-alternance",
    "category"=>"dispositif",
    "plural"=>"Contrats en alternance"}]
  }
  end

end
