FROM ruby:2.6.0

RUN apt-get update && \
    apt-get -y install bzip2 cron postgresql-client

RUN echo "0 5 * * * root bash /home/backups/backup.sh" >/etc/cron.d/backups;

CMD service cron start; \
    sleep infinity;

