# See https://stackoverflow.com/a/47642594/2595513
FROM ubuntu:16.04

ENV RBENV_ROOT=/usr/local/rbenv
ENV PATH=$RBENV_ROOT/bin:$RBENV_ROOT/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV RUBY_VERSION=2.6.0

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake curl git zlib1g-dev \
    libssl-dev libreadline-dev \
    libyaml-dev libxml2-dev \
    libxslt-dev libsqlite3-dev \
    python-dev libxml2-dev \
    libxslt-dev groff zip \
    pkg-config ca-certificates \
    && apt-get clean

# Install rbenv
RUN git clone https://github.com/rbenv/rbenv.git /usr/local/rbenv \
    && echo '# rbenv setup' > /etc/profile.d/rbenv.sh \
    && echo 'export RBENV_ROOT=/usr/local/rbenv' >> /etc/profile.d/rbenv.sh \
    && echo 'export PATH="$RBENV_ROOT/bin:$PATH"' >> /etc/profile.d/rbenv.sh \
    && echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh \
    && chmod +x /etc/profile.d/rbenv.sh


# install ruby-build
RUN mkdir /usr/local/rbenv/plugins \
    && git clone https://github.com/sstephenson/ruby-build.git /usr/local/rbenv/plugins/ruby-build \
    && /usr/local/rbenv/plugins/ruby-build/install.sh \
    && rbenv install ${RUBY_VERSION} \
    && rbenv global ${RUBY_VERSION} \
    && gem install bundler \
    && rbenv rehash

# install Rails
# RUN gem install rails -v ${RAILS_VERSION}

# Utilities
RUN apt-get -y install sudo vim telnet iputils-ping language-pack-fr ssh openssh-server

# for postgres
RUN apt-get install -y libpq-dev

# for nokogiri
RUN apt-get install -y libxml2-dev libxslt1-dev

RUN mkdir /home/clara
WORKDIR /home/clara
RUN curl https://raw.githubusercontent.com/StartupsPoleEmploi/clara/20.29.0/Gemfile -o Gemfile
RUN curl https://raw.githubusercontent.com/StartupsPoleEmploi/clara/20.29.0/Gemfile.lock -o Gemfile.lock
RUN bundle install

# wait...
CMD sleep infinity


# RUN mkdir /home/app
# WORKDIR /home/app

# RUN pwd
# RUN ls /home
# RUN pwd
# RUN bundle exec mina -v
# Run app
# EXPOSE 8080
# ADD ./.. /home/app/
# RUN useradd -m -s /bin/bash app
# WORKDIR /home/app
# RUN bundle install
# RUN ln -sf /config/database.yml $HOME/config/database.yml
# RUN ln -sf $HOME/log /log
# RUN echo '#!/bin/bash \n bundle exec rake db:migrate; RAILS_ENV=production bundle exec puma -S /var/www/ara/shared/tmp/sockets/puma.state  -C "unix:///var/www/ara/shared/tmp/sockets/puma.sock"  --pidfile /var/www/ara/shared/tmp/pids/puma.pid start' > /home/app/startup.sh; \
#     chmod +x /home/app/startup.sh
