version: "2"

services:

  srv_nginx: 
    volumes:
      - '../private/prod/nginx/clara.conf:/etc/nginx/conf.d/default.conf'
      - "../private/prod/nginx/ssl:/etc/nginx/ssl"

  srv_app: 
    volumes:
      - '../private/prod/.env:/home/clara/.env'
