version: "2.3"
services:

  reverseproxy: 
    image: nginx:1.10.3
    container_name: production_nginx
    volumes:
      - '../docker/reverseproxy/etc/nginx/sites-enabled:/etc/nginx/sites-enabled'
    ports:
      - 80:80
      - 443:443

  myapp: 
    build:
      context: .
      dockerfile: dockerfile_rails
    user: root
    volumes:
      # Git repository of the application
      - '../../clara:/var/git/ara.git'
      # Environment variables
      - '../../clara/.env:/home/clara/.env'
      # Ssh config
      - '../../clara/docker/.ssh:/root/.ssh'
    environment:
      - RAILS_ENV=production
    ports:
      - "3000:3000"
    links:
      - db3
    command: >
      sh -c "cd /var/git/ara.git &&
             bundle install &&
             service ssh restart &&
             yes y | ssh-keygen -t rsa -f ~/.ssh/id_rsa -N '' && 
             cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && 
             chmod og-wx ~/.ssh/authorized_keys && 
             echo 'My app launched !!!' &&
             sleep infinity"

  db3:
    image: postgres:9.5.17
    ports:
      - "5432:5432"
    volumes:
      - "./database/etc/postgresql/9.5/main/pg_hba.conf:/etc/postgresql/9.5/main/pg_hba.conf"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always



