version: "2.3"


services:

  reverseproxy: 
    image: nginx:1.10.3
    container_name: clara_nginx
    volumes:
      - '../docker/reverseproxy/default.conf:/etc/nginx/conf.d/default.conf'
      - '../../clara/docker/myapp:/var/www/ara'
    ports:
      - 80:80
      - 443:443
    depends_on:
      - myapp

  myapp: 
    container_name: clara_app
    build:
      context: .
      dockerfile: app.Dockerfile
    user: root
    volumes:
      - '../../clara:/var/git/ara.git'
      - '../../clara/.env:/home/clara/.env'
      # - '../../clara/docker/.ssh:/root/.ssh'
      - '../../clara/docker/myapp:/var/www/ara'
    ports:
      - "3000:3000"
    depends_on:
      - db3
    command: >
      sh -c "cd /var/git/ara.git &&
             bundle install --without development test undefined &&
             service ssh restart &&
             yes y | ssh-keygen -t rsa -f ~/.ssh/id_rsa -N '' && 
             cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && 
             chmod og-wx ~/.ssh/authorized_keys && 
             echo 'My app launched !!!' &&
             sleep infinity"

  db3:
    container_name: clara_db
    image: postgres:9.5.17
    ports:
      - "5432:5432"
    volumes:
      - "./database/etc/postgresql/9.5/main/pg_hba.conf:/etc/postgresql/9.5/main/pg_hba.conf"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
