version: "2.3"
services:
  # nginx: 
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: dockerfile_nginx
  #   ports:
  #     - "80:80"

  myapp: 
    build:
      context: .
      dockerfile: dockerfile_rails
    user: root
    volumes:
      # Git repository of the application
      - '../../clara:/var/git/ara.git'
      # Environment variables
      - '../../clara/.env:/home/clara/.env'
    links:
      - db
    command: >
      sh -c "cd /var/git/ara.git &&
             bundle install &&
             service ssh restart &&
             ssh-keygen -t rsa -f ~/.ssh/id_rsa && 
             cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys && 
             chmod og-wx ~/.ssh/authorized_keys && 
             echo 'My app launched !!!' &&
             sleep infinity"

# bundle exec mina production2 setup && 
# See https://stackoverflow.com/a/16651742/2595513
  
  db:
    image: postgres:9.5.17
    ports:
      - "5432:5432"

