version: "2"

volumes:
  vol_shared:
  vol_data:

services:

  srv_nginx: 
    image: nginx:1.10.3
    container_name: clara_nginx
    volumes:
      - 'vol_shared:/var/www/ara'
    ports:
      - 80:80
      - 443:443
    depends_on:
      - srv_app


  srv_db:
    container_name: clara_db
    image: postgres:9.5.17
    ports:
      - "5432:5432"
    volumes:
      - './db/pg_hba.conf:/etc/postgresql/9.5/main/pg_hba.conf'
      - './db/init.sql:/docker-entrypoint-initdb.d/init.sql'
      - '../latest.dump:/home/dumped/latest.dump'
      - vol_data:/var/lib/postgresql/data
    restart: always
