version: "2"

services:

  srv_app: 
    container_name: clara_app
    build:
      context: .
      dockerfile: ./app.Dockerfile
    user: root
    volumes:
      - '..:/var/git/ara.git'
      - '../.env:/home/clara/.env'
      - 'vol_shared:/var/www/ara'
    ports:
      - "3000:3000"
    depends_on:
      - srv_db
    command: >
      sh -c "chmod u+x ./allow_local_tunnel.sh && ./allow_local_tunnel.sh &&
             cd /var/git/ara.git && bundle install --without development test undefined &&
             echo 'My app launched !!!' && sleep infinity"
