version: "3"

volumes:
  vol_data:

services:
  srv_rails:
    build:
      context: .
      dockerfile: dockerfile_rails
    hostname: clara_rails
    container_name: clara_rails
    restart: always
    volumes:
      - "./rails:/home/clara"
    ports:
      - "3000:3000"

  srv_backups:
    build:
      context: .
      dockerfile: dockerfile_backups
    hostname: clara_backups
    container_name: clara_backups
    restart: always
    volumes:
      - "/mnt/backups:/mnt/backups"
      - "./backups/home/backups:/home/backups"
      - "./:/home/docker"
      #- "./rails/private/latest.dump:/home/dumped/latest.dump"

  srv_db:
    build:
      context: .
      dockerfile: dockerfile_db
    hostname: clara_db
    container_name: clara_db
    #ports:
    #  - "5432:5432"
    volumes:
    - "../private/latest.dump:/home/dumped/latest.dump"
    #  - "./database/home/dumped:/home/dumped"
    - "vol_data:/var/lib/postgresql/data"
    #  - '../private/prod/db/pg_hba.conf:/etc/postgresql/9.5/main/pg_hba.conf'
    #  - '../private/prod/db/init.sql:/docker-entrypoint-initdb.d/init.sql'
    #restart: always
    #
