version: "2.3"
services:
  # nginx: 
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: dockerfile_nginx
  #   ports:
  #     - "80:80"

  myapp: 
    build:
      context: .
      dockerfile: dockerfile_rails
    volumes:
      - '../../clara:/var/git/ara.git'
      - '../../clara/.env:/home/clara/.env'
    links:
      - db
    command: >
      sh -c "cd /var/git/ara.git &&
             bundle install &&
             echo 'My app launched !!!' &&
             sleep infinity"
# sh -c "cd /var/git/ara.git &&
#        gem install rake && 
#        gem install mina && 
#        gem install mina-multistage && 
#        gem install mina-puma && 
#        mina --version &&
#        echo 'Hello world'
#        mina production2 setup"
  
  db:
    image: postgres:9.5.17
    ports:
      - "5432:5432"

  # postgre: 
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: dockerfile_postgre
