version: "2.3"

volumes:
  vol_shared:
  vol_data:

services:

  reverseproxy: 
    image: nginx:1.10.3
    container_name: clara_nginx
    volumes:
      - '../docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - 'vol_shared:/var/www/ara'
    ports:
      - 80:80
      - 443:443
    depends_on:
      - myapp

  myapp: 
    container_name: clara_app
    build:
      context: .
      dockerfile: app.Dockerfile
    user: root
    volumes:
      - '../../clara:/var/git/ara.git'
      - '../../clara/.env:/home/clara/.env'
      - 'vol_shared:/var/www/ara'
    ports:
      - "3000:3000"
    depends_on:
      - db3
    command: >
      sh -c "chmod u+x ./deploy.sh && chmod u+x ./allow_local_tunnel.sh && ./allow_local_tunnel.sh &&
             cd /var/git/ara.git && bundle install --without development test undefined &&
             echo 'My app launched !!!' && sleep infinity"

  db3:
    container_name: clara_db
    image: postgres:9.5.17
    ports:
      - "5432:5432"
    volumes:
      - "./db/pg_hba.conf:/etc/postgresql/9.5/main/pg_hba.conf"
      - ../docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - vol_data:/var/lib/postgresql/data
    restart: always
