version: "2.3"
services:
  # nginx: 
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: dockerfile_nginx
  #   ports:
  #     - "80:80"

  rails: 
    build:
      context: .
      dockerfile: dockerfile_rails
    volumes:
      - '../../clara:/home/clara'
    links:
      - db
    command: >
      sh -c "cd /home/clara &&
             gem install pg -v '0.21.0' --source 'https://rubygems.org/'
             bundle install && 
             bundle exec mina -v"
  
  db:
    image: postgres:9.5.17
    ports:
      - "5432:5432"

  # postgre: 
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: dockerfile_postgre
