variable_list = [
  ["v_age",                      
    "âge", 
    :integer, 
    ""],
  ["v_allocation_type",
    "type d'allocation", 
    :selectionnable, 
    "ARE_ASP,ASS_AER_APS_AS-FNE,RSA,RPS_RFPA_RFF_pensionretraite,AAH,pas_indemnise"],
  ["v_allocation_value_min",
    "montant min de l'allocation", 
    :integer, 
    ""],
  ["v_category",
     "catégorie", 
     :selectionnable, 
     "cat_12345,autres_cat", 
     "catégorie 1; ou 2; ou 3; ou 4; ou 5,autres catégories"],
  ["v_diplome",                  
    "diplôme",                     
    :selectionnable, 
    "niveau_1,niveau_2,niveau_3,niveau_4,niveau_5,niveau_infra_5"],
  ["v_duree_d_inscription",      
    "durée d'inscription",         
    :selectionnable, 
    "plus_d_un_an,moins_d_un_an,non_inscrit", 
    "plus d'un an,moins d'un an,non inscrit"],
  ["v_protection_internationale",
    "protection internationale",   
    :selectionnable, 
    "oui,non"],
  ["v_handicap",                 
    "handicappé",                  
    :selectionnable, 
    "oui,non"],
  ["v_spectacle",                
    "intermittent du spectacle",   
    :selectionnable, 
    "oui,non"],
  ["v_cadre",                    
    "statut cadre",                
    :selectionnable, 
    "oui,non"],
  ["v_location_citycode",        
    "geo : code INSEE ville",      
    :string,         
    ""],
  ["v_location_zipcode",         
    "geo : code postal",           
    :string,         
    ""],
  ["v_zrr",                      
    "zone rurale prioritaire",     
    :selectionnable, 
    "oui,non"]
]

existing_variables = Variable.all.map(&:name)

variable_list.each do |name_arg, name_trans_arg, type_arg, elements_arg, elts_trans_arg|
  unless existing_variables.include?(name_arg)
    Variable.create!(
      name: name_arg, 
      name_translation: name_trans_arg, 
      variable_type: type_arg, 
      elements: elements_arg,
      elements_translation: elts_trans_arg
      )
  end
end
