version: 1
update_configs:
  - package_manager: "ruby:bundler"
    directory: "/rails"
    update_schedule: "live"
    default_reviewers:
      - "bdavidxyz"

  - package_manager: "javascript"
    directory: "/rails"
    update_schedule: "live"
    default_reviewers:
      - "bdavidxyz"
