source 'https://rubygems.org'

ruby '2.6.6'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

gem "rails", "6.0.3.2"
gem "puma"
gem "rake"
gem "uglifier"
gem "jbuilder"
gem "rack-attack"
gem "mailjet"
gem "kaminari"
gem "pg_search"
gem "rack"

gem "haml"
gem "haml-rails"
gem "sass-rails"
gem "pg"
gem "friendly_id"
gem "loofah"

gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "autoprefixer-rails"
gem "active_type"
gem "bulk_insert"
gem "gon"
gem "whenever", require: false
gem "rails-html-sanitizer"
gem "rubyzip"

gem "clipboard" # debug purpose only
gem "actionpack-page_caching"

gem "awesome_print"
gem "seed_dump"
gem "nokogiri"

## Devops
gem "newrelic_rpm"
gem "sentry-raven"
gem "ruby-prof"
gem "oj"


# Admin
gem "paper_trail", "10.3.1"
gem "administrate", "0.13.0"

gem "administrate-field-ckeditor", github: 'bdavidxyz/administrate-field-ckeditor'

gem "mina", require: false, group: "deployment"
gem "mina-puma", require: false, github: 'bdavidxyz/mina-puma', group: "deployment"
gem "mina-multistage", require: false, group: "deployment"
gem "climate_control"
gem "fuubar"
gem "dotenv-rails"
gem "knock"
gem "bcrypt"
gem "google-api-client"
gem "i18n-js"
gem "administrate_exportable", github: 'bdavidxyz/administrate_exportable'
gem "clearance"
gem "bootsnap"

gem 'administrate-field-active_storage'
gem 'image_processing'
gem 'active_storage_validations'
gem 'cloudinary'

gem 'administrate-field-paperclip'
gem 'kt-paperclip'

group :development, :test do
  gem "byebug", platform: :mri
  gem "database_cleaner"
  gem "rspec-rails"
  gem "pry-rails"
  gem "pry-stack_explorer"
  gem "pry-remote"
  gem "magic_lamp"
  gem "teaspoon-jasmine", git: 'https://github.com/bdavidxyz/teaspoon-jasmine.git'
  gem "factory_bot_rails"
end

group :test do
  gem "simplecov", require: false
  gem "capybara"
  gem "launchy"
  gem "selenium-webdriver"
  gem "poltergeist"
  gem "rack_session_access"
  gem "webmock"
  gem "coffee-rails"
  gem "mocha"
  gem "phantomjs"
end

group :development do
  gem "guard"
  gem 'guard-livereload', '~> 2.5', require: false
  gem "listen"
  gem "spring"
  gem "spring-commands-rspec"
  gem "spring-watcher-listen"
  gem "web-console"
  gem "rack-livereload"
  gem "rb-fsevent", require: false
  gem "letter_opener_web"
  gem "annotate"
end
